### ISSUE TITLE
bsub/bjobs dependency? 

### ISSUE THREAD

**Issue by j29scott** [cavalab/srbench#134]
Hi, we are trying to run the tool locally, but are running into a dependency error. We believe we followed the instructions correctly.

![image](https://user-images.githubusercontent.com/34328384/194687962-4ecfdb57-b0b7-4bb4-805b-63bb6104e91f.png)

If you comment these lines out, we get the following.

![image](https://user-images.githubusercontent.com/34328384/194688297-87420e5d-26e9-473b-bb8d-77cbe510d1c1.png)

Our intuition was we are missing some slurm dependency, but when we installed the client, the issue persisted.

**Comment by marcovirgolin** [comment]
Please try to use the flag `-local`
