### ISSUE TITLE
Always the same wrong result when trying to fit a simple ground truth equation

### ISSUE THREAD

**Issue by fnpdaml** [cavalab/srbench#141]
Hi there,

When attempting to fit the ground truth equation "3x^2 - 2x + 1" between x values of [0.0 to 10], with 60 data points, the result consistently evolves to something close to "0.297677x^2 + 0.951x -0.298461". 

Steps to reproduce:

Launch locally "evaluate_model.py" on a file with 60 data points with x values ranging from 0.0 to 10, with:
`python evaluate_model.py /pmlb/datasets/eq1/eq1.tsv -ml OperonRegressor -seed 42`
[and several other methods]

Observe that the result consistently evolves to something close to 
"0.297677x^2 + 0.951x -0.298461", 
rather than the expected 
"3x^2 - 2x + 1".

It seems we can rule out some sort of linear normalization going on.
And it's quite enough points for, say, TuringBot to find the correct solution on the same data.

- Any ideas?

Many thanks!

PS: Relevant files at this dropbox folder,
http://bit.ly/3kICKKs

**Comment by lacava** [comment]
This is a more appropriate question for https://github.com/heal-research/operon

**Comment by fnpdaml** [comment]
Hi @lacava,
It's the same wrong answer across several methods *within SRBench*.
Please reopen.

PS: I further detailed the original post.

**Comment by lacava** [comment]
SRBench provides _benchmarking tools_ for symbolic regression methods. If you have an issue with the performance of some SR methods, contact the maintainers of those methods. SRBench isn't going to make those SR methods work better on any particular problem. Only updating the methods would do that. 

I don't have any advice beyond the obvious - try more samples, create a minimum working example, visualize the iterations for a specific method, etc. Those are all off-topic for this repo.

**Comment by folivetti** [comment]
(maybe check if the evaluate script isn't normalizing the features)

**Comment by marcovirgolin** [comment]
AFAIK evaluate.py normalizes by default

**Comment by lacava** [comment]
https://github.com/cavalab/srbench/issues/139#issuecomment-1445435443

**Comment by fnpdaml** [comment]
> AFAIK evaluate.py normalizes by default

Thanks for that @marcovirgolin,
but in "experiment/evaluate.py", in line 280 and after:

```
    # check for conflicts btw cmd line args and eval_kwargs
    if args.SYM_DATA:
        eval_kwargs['scale_x'] = False
        eval_kwargs['scale_y'] = False
```

- any further ideas?

**Comment by lacava** [comment]
you have to pass the `-sym_data` flag to `evaluate_model.py` if you want to trigger that.

**Comment by lacava** [comment]
alternatively you can add `scale_x` or `scale_y` to `eval_kwargs` in the algorithms py file

**Comment by marcovirgolin** [comment]
> > AFAIK evaluate.py normalizes by default
> 
> Thanks for that @marcovirgolin, but in "experiment/evaluate.py", in line 280 and after:
> 
> ```
>     # check for conflicts btw cmd line args and eval_kwargs
>     if args.SYM_DATA:
>         eval_kwargs['scale_x'] = False
>         eval_kwargs['scale_y'] = False
> ```
> 
> Meaning normalization is disabled by default, right?
> 
> * any further ideas?

the opposite, because `-sym_data` is off by default (and `scale_x`, `scale_y` are ON)

**Comment by lacava** [comment]
1. format your `metadata.yaml` file to have an equation in the description like this: https://github.com/EpistasisLab/pmlb/blob/master/datasets/feynman_II_10_9/metadata.yaml

something like 
```yaml
dataset: eq1
description: |
Mathematical equation 

target = 3*x**2 -2*x +1 

with x between 0.0 and 10.

task: regression
target:
  type: continuous
  description: Output of the mathematical equation "3x^2 -2x +1".
features:
  - name: x
    type: continuous
    description: Input to the mathematical equation "3x^2 -2x +1".
```


3. pass the sym_data flag, and `get_sym_data` will pull the true model out of metadata.yaml. 
4. scaling should be set correctly. 

e.g. 

```
python evaluate_model.py /pmlb/datasets/eq1/eq1.tsv -ml OperonRegressor -seed 42 -sym_data
```

**Comment by fnpdaml** [comment]
Another issue: 

Your suggestion @lacava, does fix the scaling / normalization problem on many other methods, but it does fail specifically with Operon using the command you wrote, returning the error:
`ValueError: Input contains NaN, infinity or a value too large for dtype('float32')`

Not passing '-sym_data' does launch Operon on my "eq1" dataset, but then we're back at the previous situation were scaling / normalization is used. 
It works fine in other SRBench methods I tested.

Therefore, in the current state of things, one of the top methods in SRBench can only be used with auto scaling set to on (ie: not passing '-sym_data').

Compulsory normalization is problematic because if your data has a relatively low range, and, the ground truth is a relatively low order polynomial, the discriminatory ability of most symbolic regressors falls off a cliff.

- Any ideas?

Again regards and many thanks.

PS: Also, isn't the scaling expression used logged somewhere for reference?

**Comment by fnpdaml** [comment]
Also, @lacava, when trying Operon with the "192_vineyard" dataset, using: 
`python evaluate_model.py /pmlb/datasets/192_vineyard/192_vineyard.tsv.gz -ml OperonRegressor -seed 42 -sym_data`
it returns the error: 
`IndexError: list index out of range`

- Shouldn't it also work without scaling / normalization?

**Comment by foolnotion** [comment]
> Also, @lacava, when trying Operon with the "192_vineyard" dataset, using: `python evaluate_model.py /pmlb/datasets/192_vineyard/192_vineyard.tsv.gz -ml OperonRegressor -seed 42 -sym_data` it returns the error: `IndexError: list index out of range`
> 
>     * Shouldn't it also work without scaling / normalization?

When you pass `-sym_data`, the code expects a symbolic formula to be present in the description, just as @lacava indicated [above](https://github.com/cavalab/srbench/issues/141#issuecomment-1452249608). The description of `192_vineyard` does not contain the symbolic formula, therefore the code, specifically this part:
```python
 model_str = [ms for ms in description if '=' in ms][0].split('=')[-1]
```
fails (because there is no `=` in the description. Granted, the code should include some checks to protect against this, but the error you get is because you pass `-sym_data` without actually providing an appropriate data.

> Your suggestion @lacava, does fix the scaling / normalization problem on many other methods, but it does fail specifically with Operon using the command you wrote, returning the error:
ValueError: Input contains NaN, infinity or a value too large for dtype('float32')

Could you give some more detail about this error? Does it occur in Operon's sklearn module or in the SRBench code?

**Comment by fnpdaml** [comment]
Hi @foolnotion, 
I see - thanks for the clarification.

But about my ground-truth test problem, the error occurs when launching in 'srbench/experiment/':
`python evaluate_model.py /pmlb/datasets/eq1/eq1.tsv.gz -ml OperonRegressor -seed 42 -sym_data`
And it returns:
"ValueError: Input contains NaN, infinity or a value too large for dtype('float32')."

- Any ideas? 

- **Also**, when scaling is employed, where is the exact scaling expression that was used stored?

Many thanks.

PS: Again, the relevant dataset files can be found on this dropbox folder,
http://bit.ly/3kICKKs

**Comment by foolnotion** [comment]
> But about my ground-truth test problem, the error occurs when launching in 'srbench/experiment/':
python evaluate_model.py /pmlb/datasets/eq1/eq1.tsv.gz -ml OperonRegressor -seed 42 -sym_data
And it returns:
"ValueError: Input contains NaN, infinity or a value too large for dtype('float32')."
Any ideas?


I was able to reproduce this issue with Operon. This seems to happen because the prediction returned by Operon contains NaN or infinity (probably a bug, not sure). You have two options:

1. take care of it in `evaluate_model.py`:
```diff
diff --git a/experiment/evaluate_model.py b/experiment/evaluate_model.py
index 77bb385..a3c3ea1 100755
--- a/experiment/evaluate_model.py
+++ b/experiment/evaluate_model.py
@@ -191,7 +191,7 @@ def evaluate_model(dataset, results_path, random_state, est_name, est,
                               ('mae',mean_absolute_error),
                               ('r2', r2_score)
                              ]:
-            y_pred = np.asarray(pred(X)).reshape(-1,1)
+            y_pred = np.nan_to_num(pred(X)).reshape(-1,1)
             if scale_y:
                 y_pred = sc_y.inverse_transform(y_pred)
             results[score + '_' + fold] = scorer(target, y_pred) 
```

2. use a newer version of Operon

> Also, when scaling is employed, where is the exact scaling expression that was used stored?

I am not sure what you mean by that? The `StandardScaler()` objects `sc_X` and `sc_Y` hold the scaling information and can be used later to perform the inverse operation.
