### ISSUE TITLE
Feature renaming issue

### ISSUE THREAD

**Issue by kartelj** [cavalab/srbench#142]
Hi, 

I believe you have an issue at this line:
https://github.com/cavalab/srbench/blob/a7875bf10f139d3e16dff9bca1779f211a8763b6/experiment/symbolic_utils.py#L158

Here are the steps to reproduce it:

instance: feynman_I_11_19
candidate model: x0\*x3 + x1\*x4 + x2\*x5
true model: x1\*y1+x2\*y2+x3\*y3
yaml features order: x1, x2, x3, y1, y2, y3 == x0, x1, x2, x3, x4, x5

replacing feature 0 with x1
x1\*x3+x1\*x4+x2\*x5

replacing feature 1 with x2
x2\*x3+x2\*x4+x2\*x5

replacing feature 2 with x3
x3\*x3+x3\*x4+x3\*x5

replacing feature 3 with y1
y1\*y1+y1\*x4+y1\*x5

replacing feature 4 with y2
y1\*y1+y1\*y2+y1\*x5

replacing feature 5 with y3
y1\*y1+y1\*y2+y1\*y3

So, the candidate model x0\*x3 + x1\*x4 + x2\*x5 is renamed to y1\*y1+y1\*y2+y1\*y3, which is obviously not the same thing. 

The possible fix would be to perform renaming backwards. 
for i,f in enumerate(features):  --> for i,f in reversed(list(enumerate(features))):  

Now, the steps will be:
replacing feature 5 with y3
x0\*x3+x1\*x4+x2\*y3

replacing feature 4 with y2
x0\*x3+x1\*y2+x2\*y3

replacing feature 3 with y1
x0\*y1+x1\*y2+x2\*y3

replacing feature 2 with x3
x0\*y1+x1\*y2+x3\*y3

replacing feature 1 with x2
x0\*y1+x2\*y2+x3\*y3

replacing feature 0 with x1
x1\*y1+x2\*y2+x3\*y3

Best regards,
Aleksandar

**Comment by lacava** [comment]
thanks for the catch!
