### ISSUE TITLE
run the ML method ------metadata.yaml not found

### ISSUE THREAD

**Issue by wencyxu** [cavalab/srbench#168]
<img width="696" alt="微信图片_20240124212312" src="https://github.com/cavalab/srbench/assets/116553156/762015f0-e06b-4566-bce7-968e3cae1b17">
When I run "python analyze.py /root/SP500/B1.tsv.gz -ml 'AdaBoostRegressor", it shows:Metadata file /root/SP500/metadata.yaml not found, skipping dataset /root/SP500/B1.tsv.gz.
How do I run the ML method, please?
Thanks a lot!!!!

**Comment by lacava** [comment]
1. what version are you using? (recommend release)
2. `analyze.py` expects a dataset directory, not a single data file. and it expects to submit to a cluster unless you pass `--local` flag.

**Comment by wencyxu** [comment]
<img width="717" alt="微信图片_20240125092712" src="https://github.com/cavalab/srbench/assets/116553156/ef9aa28b-fde2-4f30-a08e-b06dc6925810">
<img width="396" alt="微信图片_20240125092719" src="https://github.com/cavalab/srbench/assets/116553156/8c11d49b-9dd5-4ea0-ae8c-66a7660fd1a8">Thank you so much for receiving your reply ~ I have one more small question. As shown in the picture, I entered a dataset directory (containing tsv.gz and metadata.yaml), but it shows that the folder does not have a dataset.

**Comment by folivetti** [comment]
have you cloned the pmlb repository using git-lfs?

https://github.com/EpistasisLab/pmlb?tab=readme-ov-file#datasets

**Comment by wencyxu** [comment]
No, I haven't. Because I wanted to use my own dataset instead of PMLB.

**Comment by lacava** [comment]
https://github.com/cavalab/srbench/blob/f9fb2ba39d33ecabdc544f839008f13dca09ce29/experiment/analyze.py#L20
https://github.com/cavalab/srbench/blob/f9fb2ba39d33ecabdc544f839008f13dca09ce29/experiment/analyze.py#L21

pmlb/datasets looks like this: https://github.com/EpistasisLab/pmlb/tree/master/datasets

i.e., put your data in a data folder, and pass the parent folder. 

if you aren't using the [release version](https://github.com/cavalab/srbench/releases/tag/v2.0) you may run into other issues.

**Comment by wencyxu** [comment]
Thanks a lot!!!😀I can run ML methods now.
