### ISSUE TITLE
where is the .src.ITEA?

### ISSUE THREAD

**Issue by wencyxu** [cavalab/srbench#170]
<img width="788" alt="微信图片_20240130205708" src="https://github.com/cavalab/srbench/assets/116553156/3ad2a931-b240-4ce4-a9b6-e2cccce24a93">
I have another small question: where is the .src.ITEA module?  Could you take a look,please?Thanks a lot~

**Comment by lacava** [comment]
please include the version you are using in the issue


https://github.com/cavalab/srbench/blob/v2.0/experiment/methods/src/itea_install.sh
- @folivetti do you know what commit hash matches v2.0 of srbench?

**Comment by folivetti** [comment]
ah yes, true. This has changed throughout history.

It should be this commit https://github.com/folivetti/ITEA/tree/6e76b2d8fbaecc51bde548f6400f075b8a1940dd
