### ISSUE TITLE
Singularity container for srbench

### ISSUE THREAD

**Issue by justbennet** [cavalab/srbench#172]
I am the system administrator at a smallish HPC site.  We have a research group that would like to use `srbench`.  We are, unfortunately, currently stuck on RHEL 7 (ancient) for the host operating system on our cluster machines.  We were unable to get the environment to resolve to a working, native installation, so I turned to [lacava/srbench:latest](https://hub.docker.com/layers/lacava/srbench/latest/images/sha256-bab47255e3e4f7e01edeb36665050864a62677418cfff95a39d2b91029a5f5d6?context=explore), from which I create a Singularity container.

The container seems to have a working version of srbench, once I activate the `srbench` conda environment, at least insofar as it will print the help from `python analyze.py`.

```
$ singularity shell /gpfs1/cont/srbench/srbench.sif 
Singularity> eval "$('/opt/conda/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
Singularity> conda activate srbench
(srbench) Singularity> cd /experiment
(srbench) Singularity> python analyze.py -h | head -5
usage: analyze.py [-h] [-ml LEARNERS] [--local] [--slurm] [--noskips]
                  [-skip_tuning] [-A A] [-sym_data] [-tuned] [-n_jobs N_JOBS]
. . . .
```

It seems that the algorithms are not installed so the Docker container is incomplete?

I may be misreading things, too, but the install.sh script goes on to this check if given no arguments

```
if (($#==1)); #check if number of arguments is 1 
then
    subnames=($1)
else
    subnames=$(ls algorithms/)
fi
```
but there is no `algorithms` directory in the docker container.

Everything seems very tuned to a local conda installation from a clone of the Github repository, and I'm struggling a bit to get the Docker container to work.  Is there a documented procedure for picking up the installation using Docker for all the algorithms?

I hope I'm not missing something really obvious.

**Comment by lacava** [comment]
hey @justbennet , sorry for delay on this. i imagine you were you able to solve your issue?

the docker env came about after the initial project, which was based on a single local conda install as you mentioned. we're been working to move each alg to its own docker environment over the last couple months.
