### ISSUE TITLE
About Datasets

### ISSUE THREAD

**Issue by 1583364217** [cavalab/srbench#173]
Hello author, your job is very good. I encountered some problems during verification and hope to be able to answer them. In the project, there are a total of 252 sets of data, including 122 black boxes and 130 ground truth, of which 122 are from PMLB and 130 are from AI feynman and ode. The ode states that the data has been added to PMLB. May I ask if the data from AI feynman has been added to PMLB, and if all 252 sets of data I need can be obtained from PMLB? Currently, PMLB has 255 sets. Can I know which three sets are not needed, or if AI feynman has not been added, so there is data in PMLB that is not in SRBENCH? Can I provide a list for PMLB? What data is SRbench and which data is SRbench in AI feynman. Could you please answer any doubts

**Comment by 1583364217** [comment]
When reproducing the 2022 competition, I saw that the dataset solved my doubts. I have another question, is this SRBench2022 that I can only replicate on my own machine? Can I submit the results to the website for output? I want to use a faster running speed. If I can't run the same device on the website, I can only run it all on my own machine. Can SRBench2022 still be submitted online now?

**Comment by hengzhe-zhang** [comment]
Hi @1583364217, I just want to mention one point: The PMLB should have 120 datasets because 2 datasets that were included are actually classification datasets, and they have been removed. Please see [this issue](https://github.com/EpistasisLab/pmlb/issues/162).

**Comment by lacava** [comment]
PMLB has feynman and ode datasets integrated.

**Comment by lacava** [comment]
srbench 2022 competition is closed. we have specific organized benchmarks from time to time but we don't have the infrastructure to produce full experiment results on new methods automatically by submitting them.
