### ISSUE TITLE
Anaconda may stop being free

### ISSUE THREAD

**Issue by folivetti** [cavalab/srbench#181]
Not sure if that's an issue that would affect us, but Anaconda seems to be trying to charge universities and researchers that make use of Anaconda.

More info: https://www.theregister.com/2024/08/08/anaconda_puts_the_squeeze_on/

maybe with the docker it can be a good opportunity to move away from conda

**Comment by lacava** [comment]
I could be mistaken, but I don't think this applies to us. The current build process uses micromamba and/or mambaforge.
