### ISSUE TITLE
Request for Instructions on How To run *just one* of the Experiments - to validate/debug the installation

### ISSUE THREAD

**Issue by doliveira4** [cavalab/srbench#88]
Hi there,

Would it be possible to add to your instructions 
how to exactly run *just one* of the several Experiments?
Perhaps the simplest, fastest, non-empty, experiment - just for validation?

I can't get docker to finish executing, so I need to debug / validate my installation of 'srbench'.
I'm completely new to this toolchain, so a bit lost.

Many thanks.

**Comment by folivetti** [comment]
in my experiments I executed the following steps for each dataset and seed:

```bash
source activate srbench
cd srbench/experiment
python evaluate_model.py ~/pmlb/datasets/192_vineyard/192_vineyard.tsv.gz -ml OperonRegressor -seed 11284
```

assuming that the datasets are at your home directory. You should replace OperonRegressor with your own regressor.

**Comment by lacava** [comment]
Also check the CI, which ones run experiment (very similar to above). this
is in test_evaluate_model.py

**Comment by Leoningel** [comment]
Where can I find the used datasets?

**Comment by Leoningel** [comment]
Nevermind, found it (https://github.com/EpistasisLab/pmlb/tree/master)

**Comment by lacava** [comment]
appears resolved
