### ISSUE TITLE
this is terrible

### ISSUE THREAD

**Issue by janoPig** [cavalab/srbench#99]
I think this is terrible. 
def model(est, X):
    mapping = {'x_'+str(i):k for i,k in enumerate(X.columns)}
    new_model = est.model_
    for k,v in mapping.items():
        new_model = new_model.replace(k,v)

replace x_1? if exist x_11?

simple this is solution:
 for k, v in reversed(mapping.items()):

**Comment by lacava** [comment]
hi @janoPig 

[please review ground rule #3](https://cavalab.org/srbench/contributing/#ground-rules)

if you want to be a jerk, do it somewhere else 

thanks for the fix

**Comment by foolnotion** [comment]
@janoPig thank you for the bug report. in the future please try to add helpful and descriptive titles to your issues.

 the presented snippet is illustrative only as we cannot know how you decide to name your variables internally in your model. the criteria for returning a sympy-compatible model string are clearly described in the competition guidelines.
